Fix unexpected key pixel_metrics.AUPRO.fpr_limit
openvinotoolkit/anomalib pull request #1055
Opened 2023-04-27 15:03 UTC by WenjingKangIntel

# Description

- Provide a summary of the modification as well as the issue that has been resolved. List any dependencies that this modification necessitates.
AUPRO's fpr_limit is serialized into checkpoint during training however when loading from state_dict with strict mode for testing, if the AnomalyModule instance has not have such attr, it will trigger error. This PR add the attribute before loading from checkpoint. 
- Fixes #988

## Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which refactors the code base)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the [pre-commit style and check guidelines](https://github.com/openvinotoolkit/anomalib/blob/main/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] I have added a summary of my changes to the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) (not for minor changes, docs and tests).

2023-04-28 07:43 UTC, ashwinvaidya17 requested changes
We are planning on removing metrics from the anomaly module and making it part of the trainer. But for now this is a necessary fix. Thanks for the changes. We should also include a test that checks this fix. Otherwise, this might end up silently breaking in the future again.

2023-04-28 07:43 UTC, ashwinvaidya17 commented on src/anomalib/models/components/base/anomaly_module.py
> +            self.pixel_metrics.add_metrics(AUPRO(fpr_limit=fpr_limit))
I am in favour of something more generic and less hard-coded. Maybe something like
```python
def _load_metrics(self, state_dict: OrderedDict[str, Tensor]) -> None:
        """Create pixel_metrics and add AUPRO."""
        self._set_metrics("pixel", state_dict)
        self._set_metrics("image", state_dict)

    def _set_metrics(self, name: str, state_dict: OrderedDict[str, Tensor]):
        """Sets the pixel/image metrics.

        Args:
        name (str): is it pixel or image.
        state_dict (OrderedDict[str, Tensor]): state dict of the model.
        """
        metric_keys = [key for key in state_dict.keys() if key.startswith(f"{name}_metrics")]
        if not hasattr(self, f"{name}_metrics") and any(metric_keys):
            metrics = AnomalibMetricCollection([], prefix=f"{name}_")
            for key in metric_keys:
                class_name = key.split(".")[1]
                try:
                    metrics_module = importlib.import_module("anomalib.utils.metrics")
                    metrics_cls = getattr(metrics_module, class_name)
                except Exception as exception:
                    raise ImportError(f"Class {class_name} not found in module anomalib.utils.metrics") from exception
                metrics.add_metrics(metrics_cls())
            setattr(self, f"{name}_metrics", metrics)
```

2023-04-28 09:53 UTC, ashwinvaidya17 approved these changes
Thanks

2023-04-28 09:54 UTC, ashwinvaidya17 requested changes
Sorry, but can you also add a test for this

2023-04-28 11:13 UTC, samet-akcay approved these changes

2023-05-01 07:18 UTC, ashwinvaidya17 approved these changes
Thanks

2023-05-19 14:43 UTC, djdameln approved these changes

2023-10-24 10:15 UTC, merged

2023-11-12 11:57 UTC, 1094558673 commented
@WenjingKangIntel Hello, I also encountered an Unexpected key(s) in state_dict: "pixel_metrics.AUPRO.fpr_limit" when I was inferring.

The specific inference commands are:
python tools/inference/lightning_inference.py --config src/anomalib/models/efficient_ad/config-rail.yaml --weights  results/efficient_ad/sound/run/weights/lightning/model-v27.ckpt --input datasets/sound/abnormal-aug-cutpic --output  infer/2

So, I modified the code as you provided, but the problem doesn't seem to be solved. Looking forward to your reply, the relevant contents of my config.yaml file are:
metrics:
image:
- AUROC
pixel:
- AUROC
- AUPRO