Fix Fastflow ONNX export.
openvinotoolkit/anomalib pull request #1108
Opened 2023-05-26 12:08 UTC by jasonvanzelm

# Description

- Provide a summary of the modification as well as the issue that has been resolved. List any dependencies that this modification necessitates.

- Fixes #1096 

## Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which refactors the code base)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the [pre-commit style and check guidelines](https://github.com/openvinotoolkit/anomalib/blob/main/CONTRIBUTING.md) of this project.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] I have added a summary of my changes to the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) (not for minor changes, docs and tests).

2023-05-28 21:55 UTC, blaz-r commented
Looks good. From what I tested it works ok, but at some point there is some difference on 7th decimal which probably won't cause problems. According to this https://github.com/pytorch/pytorch/pull/89107 "same" will be supported in PyTorch 2.1, but in the meantime this workaround look great.

2023-05-30 05:41 UTC, samet-akcay commented
> Looks good. From what I tested it works ok, but at some point there is some difference on 7th decimal which probably won't cause problems. According to this [pytorch/pytorch#89107](https://github.com/pytorch/pytorch/pull/89107) "same" will be supported in PyTorch 2.1, but in the meantime this workaround look great.

Looks like PyTorch v2.1 will be released some time in october. Meanwhile, we could use this approach to tackle this issue.

2023-05-30 05:42 UTC, samet-akcay approved these changes
@jasonvanzelm, thanks for your contribution!

2023-05-30 05:43 UTC, samet-akcay commented on src/anomalib/models/fastflow/torch_model.py
> +        # setting padding="same" in nn.Conv2d breaks the onnx export so we pad by hand
```suggestion
        # NOTE: setting padding="same" in nn.Conv2d breaks the onnx export so manual padding required.
        # TODO: Use padding="same" in nn.Conv2d once PyTorch v2.1 is released
```

2023-05-30 05:44 UTC, samet-akcay requested changes
sorry, just noticed a minor issue here

2023-06-04 13:54 UTC, merged