🛠️ Refactor: Spilt models to image and video
openvinotoolkit/anomalib pull request #1493
Opened 2023-11-20 22:07 UTC by samet-akcay

## Description

- Split anomalib models to image and video.

The following is the new structure after the refactor

```bash
src/anomalib/models
├── components
│   ├── base
│   ├── classification
│   ├── cluster
│   ├── dimensionality_reduction
│   ├── feature_extractors
│   ├── filters
│   ├── flow
│   ├── __init__.py
│   ├── layers
│   ├── sampling
│   └── stats
├── image
│   ├── cfa
│   ├── cflow
│   ├── csflow
│   ├── dfkde
│   ├── dfm
│   ├── draem
│   ├── efficient_ad
│   ├── fastflow
│   ├── ganomaly
│   ├── __init__.py
│   ├── padim
│   ├── patchcore
│   ├── README.md
│   ├── reverse_distillation
│   ├── rkde
│   └── stfpm
├── __init__.py
└── video
    ├── ai_vad
    └── __init__.py
```

2023-11-21 08:58 UTC, djdameln commented on src/anomalib/models/image/README.md
A similar README for video would be nice

2023-11-21 11:38 UTC, samet-akcay commented on src/anomalib/models/image/README.md
I have now added a `README.md` for the video stuff as well.

2023-11-21 13:01 UTC, djdameln requested changes
1 minor comment

2023-11-21 13:05 UTC, djdameln commented on src/anomalib/models/video/README.md
> +datamodule = Avenue()
We could also make this the default behaviour of `Avenue`. If we decide this, then we should do the same for `ShanghaiTech` (`UCSDped` already has this as the default behaviour)

2023-11-21 13:06 UTC, samet-akcay commented on src/anomalib/models/video/README.md
> +datamodule = Avenue()
I think this would be a scope of another pr?

2023-11-21 13:06 UTC, samet-akcay commented on src/anomalib/models/video/README.md
> +datamodule = Avenue()
or is it just setting the default parameter to ?

2023-11-28 12:05 UTC, djdameln approved these changes

2023-11-28 15:59 UTC, merged