Test OpenVINO export
openvinotoolkit/anomalib pull request #1681
Opened 2024-01-26 14:55 UTC by adrianboguszewski

## 📝 Description

@samet-akcay @ashwinvaidya17 is it the right place to test if all models are exportable to OpenVINO?

## ✨ Changes

Select what type of change your PR is:

- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔨 Refactor (non-breaking change which refactors the code base)
- [x] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] 📚 Documentation update
- [ ] 🔒 Security update

## ✅ Checklist

Before you submit your pull request, please make sure you have completed the following steps:

- [ ] 📋 I have summarized my changes in the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) and followed the guidelines for my type of change (skip for minor changes, documentation updates, and test enhancements).
- [ ] 📚 I have made the necessary updates to the documentation (if applicable).
- [ ] 🧪 I have written tests that support my changes and prove that my fix is effective or my feature works (if applicable).

2024-01-28 06:17 UTC, samet-akcay requested changes
Thanks @adrianboguszewski. I have one suggestion to rename framework to export_type. Since framework term is not used in the main code base, the code might flow better if we stick to the `export_type` term that is used throughout the codebase

2024-01-28 06:17 UTC, samet-akcay commented on tests/integration/model/test_models.py
> +        export_framework: ExportType,
```suggestion
        export_type: ExportType,
```

2024-01-28 06:17 UTC, samet-akcay commented on tests/integration/model/test_models.py
> +def frameworks() -> list[ExportType]:
how about the one below to follow the existing terminology?
```suggestion
def export_types() -> list[ExportType]:
```

2024-01-28 06:17 UTC, samet-akcay commented on tests/integration/model/test_models.py
> +    @pytest.mark.parametrize("export_framework", frameworks())
```suggestion
    @pytest.mark.parametrize("export_type", export_types())
```

2024-02-09 16:50 UTC, adrianboguszewski commented
@samet-akcay you review has been incorporated :)

2024-02-09 17:22 UTC, samet-akcay approved these changes

2024-02-13 21:17 UTC, merged

2024-02-14 23:38 UTC, nguyenanhtuan1008 commented
@adrianboguszewski @samet-akcay 
sorry, I have a question. I used command line for training: anomalib train --config <path/to/config>. Now I want to export the custom model to TORCH and OpenVINO model, how can I do it? 

This my command:
anomalib train --config /workspaces/anomalib/efficient_ad.yaml --data /workspaces/anomalib/mvtec.yaml 

mvtec.yaml:
```
model:
  class_path: anomalib.models.EfficientAd
  init_args:
    teacher_out_channels: 384
    model_size: M
    lr: 0.0001
    weight_decay: 1.0e-05
    padding: false
    pad_maps: true
    batch_size: 1

metrics:
  pixel:
    - AUROC

trainer:
  max_epochs: 1000
  max_steps: 70000

```

and efficient_ad.yaml:
```
model:
  class_path: anomalib.models.EfficientAd
  init_args:
    teacher_out_channels: 384
    model_size: M
    lr: 0.0001
    weight_decay: 1.0e-05
    padding: false
    pad_maps: true
    batch_size: 1

metrics:
  pixel:
    - AUROC

trainer:
  max_epochs: 1000
  max_steps: 70000

```