Visualizer show classification and segmentation
openvinotoolkit/anomalib pull request #178
Opened 2022-03-30 14:11 UTC by alexriedel1

This would be a possible fix to https://github.com/openvinotoolkit/anomalib/pull/175#issuecomment-1082988190

Alternatively, the classification image could always be added as it provides useful insights in what the model predicted.

2022-03-30 15:26 UTC, alexriedel1 commented on anomalib/utils/callbacks/visualizer_callback.py
> +                    image=image, text=f'Pred: {outputs["pred_scores"][i]:.3f} GT: {int(outputs["label"])}'
should be `outputs["label"][i]`

2022-04-01 12:10 UTC, samet-akcay requested changes
Thanks for the pr, would you be able to resolve the merge conflicts so we could run the CI?

2022-04-01 12:14 UTC, alexriedel1 commented
> Thanks for the pr, would you be able to resolve the merge conflicts so we could run the CI?

Ah right! Just want to note that after merging this PR https://github.com/openvinotoolkit/anomalib/pull/181 the proposed solution needs to be updated..

2022-04-05 18:49 UTC, samet-akcay commented
@alexriedel1, the CI has been fixed now. Could you please update the PR by pulling the latest development? Thanks!

2022-04-05 18:51 UTC, alexriedel1 commented
> @alexriedel1, the CI has been fixed now. Could you please update the PR by pulling the latest development? Thanks!

done

2022-04-06 08:06 UTC, alexriedel1 commented
I merged the development branch and fixed some styling errors

2022-04-06 14:07 UTC, samet-akcay commented
@alexriedel1, we've run the CI. There are two tests that failed unexpectedly. We'll have a look why this is the case, and let you know. I don't expect you to look the tests:)

Here is the CI log showing why it failed:
[CI-PR-178.log](https://github.com/openvinotoolkit/anomalib/files/8427540/CI-PR-178.log)

2022-04-06 14:15 UTC, alexriedel1 commented
> @alexriedel1, we've run the CI. There are two tests that failed unexpectedly. We'll have a look why this is the case, and let you know. I don't expect you to look the tests:)
> 
> Here is the CI log showing why it failed: [CI-PR-178.log](https://github.com/openvinotoolkit/anomalib/files/8427540/CI-PR-178.log)

It's because the class `VisualizerCallback` now has to be initialized with a task. I can check that and fix it if you want.

2022-04-06 14:41 UTC, ashwinvaidya17 approved these changes
Thanks for the efforts!

2022-04-06 15:05 UTC, djdameln approved these changes
Thanks for another nice contribution. I just have some minor comments

2022-04-07 13:44 UTC, alexriedel1 commented on anomalib/utils/callbacks/visualizer_callback.py
> +                true_mask = outputs["mask"][i].cpu().numpy()
I corrected the image order but also realized that classification is always possible, so why not display the classified image in either case

2022-04-07 13:44 UTC, alexriedel1 commented on anomalib/utils/callbacks/visualizer_callback.py
> +                    image=image, text=f'Pred: {outputs["pred_scores"][i]:.3f} GT: {int(outputs["label"][i])}'
Added the proposed labels (its a pain to write on images using cv2..)

2022-04-08 06:33 UTC, merged