Fix docstrings
openvinotoolkit/anomalib pull request #22
Opened 2021-12-10 16:10 UTC by ashwinvaidya17

# Changes

- Addresses doc string issues.

# Known Issues

- We can add more examples to the docstring.

2021-12-13 11:27 UTC, djdameln commented on anomalib/core/callbacks/model_loader.py
> +        Loads the model weights from into the PyTorch module.
Something's missing between `from` and `into`

2021-12-13 11:36 UTC, djdameln commented on anomalib/core/model/kde.py
> +            bias (Optional[bool]):  (Default value = False)
Can you add a description for this parameter?

2021-12-13 12:11 UTC, djdameln commented on anomalib/models/dfkde/normality_model.py
>            max_length: Optional[Tensor]:  (Default value = None)
Descriptions are missing here

2021-12-13 12:15 UTC, djdameln commented
Few minor comments

2021-12-13 12:16 UTC, ashwinvaidya17 commented on anomalib/models/dfkde/normality_model.py
>            max_length: Optional[Tensor]:  (Default value = None)
Thanks! I missed these.

2021-12-13 12:32 UTC, samet-akcay commented on anomalib/models/dfm/dfm_model.py
> +            C = X.X^T
maybe we could have these equations within quotes to properly render in the docs

2021-12-13 12:32 UTC, samet-akcay commented on anomalib/models/dfm/dfm_model.py
> +            C = X.X^T
like `C = X.X^T`?

2021-12-13 12:35 UTC, samet-akcay commented on anomalib/models/dfm/model.py
> +          _ (int): Index of the batch.
We could remove this. It'll appear in the documentation, which won't make sense to the reader.

2021-12-13 12:38 UTC, samet-akcay requested changes
only couple of minor comment

2021-12-24 10:09 UTC, samet-akcay approved these changes

2021-12-27 10:01 UTC, djdameln approved these changes

2021-12-27 10:04 UTC, merged