Fix inconsistent benchmarking throughput/time
openvinotoolkit/anomalib pull request #221
Opened 2022-04-11 14:59 UTC by ashwinvaidya17

# Description

- Supress outputs from model and print values from benchmarking script

- Fixes #185 

## Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the [pre-commit style and check guidelines](https://openvinotoolkit.github.io/anomalib/guides/using_pre_commit.html#pre-commit-hooks) of this project.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes

2022-04-11 15:36 UTC, samet-akcay commented on tools/benchmarking/benchmark.py
> +    print(model_config.model.name, model_config.dataset.category)
What if we want to run `benchmark.py` for custom datasets that don't have `category` field?

2022-04-11 15:36 UTC, samet-akcay commented on tools/benchmarking/benchmark.py
> +logging.getLogger("os").setLevel(logging.ERROR)
maybe we could set the level in a for loop to avoid the duplicated lines

2022-04-12 07:32 UTC, samet-akcay requested changes
Thanks, just minor stuff

2022-04-12 10:49 UTC, djdameln reviewed
This works, but there will still be inconsistency in the throughput numbers between a normal training run and the benchmarking script. Maybe to avoid confusion, you could also add the batch size to the output in the timer callback Something like `Throughput (batch_size=16): 12 FPS`

2022-04-12 11:12 UTC, djdameln approved these changes

2022-04-12 12:24 UTC, merged