Refactor and restructure anomalib.data
openvinotoolkit/anomalib pull request #2302
Opened 2024-09-10 15:19 UTC by samet-akcay

## 📝 Description

- Split Torch datasets and Lightning Datamodules into `datasets` and `datamodules`
- Move `dataclasses` into `data` 

## ✨ Changes

Select what type of change your PR is:

- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [x] 🔨 Refactor (non-breaking change which refactors the code base)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 Documentation update
- [ ] 🔒 Security update

## ✅ Checklist

Before you submit your pull request, please make sure you have completed the following steps:

- [ ] 📋 I have summarized my changes in the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) and followed the guidelines for my type of change (skip for minor changes, documentation updates, and test enhancements).
- [ ] 📚 I have made the necessary updates to the documentation (if applicable).
- [ ] 🧪 I have written tests that support my changes and prove that my fix is effective or my feature works (if applicable).

For more information about code review checklists, see the [Code Review Checklist](https://github.com/openvinotoolkit/anomalib/blob/main/docs/source/markdown/guides/developer/code_review_checklist.md).

2024-09-10 15:57 UTC, djdameln requested changes
As discussed, I'm in favor of this new structure. It seems the `datasets` submodule is missing though.

2024-09-10 16:00 UTC, samet-akcay commented
> As discussed, I'm in favor of this new structure. It seems the `datasets` submodule is missing though.

no idea what's wrong though. Tests locally pass 🙃

2024-09-11 07:53 UTC, ashwinvaidya17 approved these changes
So from what I understand, the intent of the PR is to split data into dataclasses and datamodules?

2024-09-11 07:53 UTC, ashwinvaidya17 commented on src/anomalib/data/datamodules/base/__init__.py
> +# Copyright (C) 2022 Intel Corporation
```suggestion
# Copyright (C) 2022-2024 Intel Corporation
```

2024-09-11 07:59 UTC, samet-akcay commented
> So from what I understand, the intent of the PR is to split data into dataclasses and datamodules?

and also datasets. Overall, data will contain the dataclasses (item, batch etc.), datasets (torch) and datamodules (lightning)

2024-09-11 09:53 UTC, djdameln approved these changes

2024-09-11 11:35 UTC, merged