✨ Add hash check to data download
openvinotoolkit/anomalib pull request #284
Opened 2022-04-26 09:47 UTC by ashwinvaidya17

# Description

- Check hash for files downloaded from remote location.

- Fixes #253 

## Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the [pre-commit style and check guidelines](https://openvinotoolkit.github.io/anomalib/guides/using_pre_commit.html#pre-commit-hooks) of this project.
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes

2022-04-26 14:06 UTC, samet-akcay requested changes

2022-04-26 14:06 UTC, samet-akcay commented on anomalib/data/mvtec.py
> +            hash_check(self.root / dataset_name, "eefca59f2cede9c3fc5b6befbfec275e")
quite minor, but btech has `zip_filename`, would be good if the two has consistent implementation, (ie., both has `zip_filename` or path)

2022-04-26 15:40 UTC, djdameln requested changes

2022-04-26 15:40 UTC, djdameln commented on anomalib/data/utils/download.py
> +        ), f"Downloaded file {file_path} does match the required hash."
this should be "does not match"

2022-04-26 18:25 UTC, ashwinvaidya17 commented on anomalib/data/utils/download.py
> +        ), f"Downloaded file {file_path} does match the required hash."
🙃

2022-04-29 07:23 UTC, samet-akcay approved these changes

2022-04-29 07:23 UTC, samet-akcay approved these changes

2022-04-29 07:24 UTC, djdameln approved these changes

2022-04-29 07:24 UTC, merged