Da/inference documentation
openvinotoolkit/anomalib pull request #308
Opened 2022-05-11 15:55 UTC by djdameln

# Description

- Adds documentation for export, optimization and inference. Should probably be merged after https://github.com/openvinotoolkit/anomalib/pull/298, since it describes the new pytorch inferencer format.

## Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the [pre-commit style and check guidelines](https://openvinotoolkit.github.io/anomalib/guides/using_pre_commit.html#pre-commit-hooks) of this project.
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes

2022-05-12 08:51 UTC, ashwinvaidya17 requested changes
Looks good. Only one comment

2022-05-12 08:51 UTC, ashwinvaidya17 commented on docs/source/guides/inference.rst
> +| meta_data   | False    | Path to the JSON file containing the model's meta data (e.g. normalization          |
This should be true

2022-05-13 06:50 UTC, ashwinvaidya17 commented
I just realized that you need to refer these files in `index.rst` as well

We have a guides section
```rst
   guides/developing_on_docker
   guides/structure_of_documentation
   guides/using_tox
   guides/using_pre_commit
   guides/inference <-- you need to add here
   guides/export
```

2022-06-08 11:21 UTC, samet-akcay approved these changes

2022-06-08 11:26 UTC, ashwinvaidya17 approved these changes

2022-06-08 11:26 UTC, merged