Document the usage of timm as backbone provider
openvinotoolkit/anomalib pull request #544
Opened 2022-09-07 07:46 UTC by jpcbertoldo

# Description

Add some text in the documentation to make it clearer that timm is used to fetch pre-trained models.

- Fixes #543

## Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which refactors the code base)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [X] Documentation improvement

## Checklist

- [ ] My code follows the [pre-commit style and check guidelines](https://openvinotoolkit.github.io/anomalib/guides/using_pre_commit.html#pre-commit-hooks) of this project.
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [X] N/A

2022-09-09 08:47 UTC, djdameln commented on README.md
> +# Feature extraction & (pre-trained) backbones
The formatting is a bit off here. I think this header
`## Custom Dataset`
should be placed under your section, and
`# Feature extraction & (pre-trained) backbones`
should be 
`## Feature extraction & (pre-trained) backbones`

2022-09-09 09:36 UTC, ashwinvaidya17 requested changes
Thanks for updating the documentation! I have a minor comment.

2022-09-09 09:36 UTC, ashwinvaidya17 commented on docs/source/models.rst
> +For an introductiont to timm, please check the `Getting Started with PyTorch Image Models (timm): A Practitioner’s Guide <https://towardsdatascience.com/getting-started-with-pytorch-image-models-timm
Typo `introductiont` -> `introduction`

2022-09-09 20:00 UTC, jpcbertoldo reviewed
requested changes done

2022-09-22 11:41 UTC, ashwinvaidya17 commented
@jpcbertoldo can you have a look at the issues raised by codacy?

2022-09-22 11:43 UTC, jpcbertoldo commented
I'll try if i have time today.
Btw tests were failing in my local env.
I think it was in the other branch but it wasn't related to my changes. 
I was wondering if we could arrange a call so i can get a hand with that.

2022-09-22 11:52 UTC, ashwinvaidya17 commented
> I'll try if i have time today. Btw tests were failing in my local env. I think it was in the other branch but it wasn't related to my changes. I was wondering if we could arrange a call so i can get a hand with that.

Sure take your time. I just ran the CI and I can see that it fails for linting checks but we can have a call in case `tox` is not working on your machine. Maybe we might have to update the documentation. Let's continue that discussion in an email thread.

2022-09-26 08:36 UTC, jpcbertoldo commented
this was integrated in #576

2022-09-26 08:36 UTC, closed without merging

2024-11-01 03:41 UTC, watertianyi commented
I used convnextv2_huge.fcmae_ft_in22k_in1k_512 to replace the pre-trained network wide_resnet50_2 in patchcore, and used layers=['stages.1', 'stages.2'] for classification. The indicator effect is far worse than wide_resnet50_2. Isn't convnextv2 better than wide_resnet50_2? Why Would it be so bad?