padim arguments improvements
openvinotoolkit/anomalib pull request #664
Opened 2022-11-01 01:26 UTC by jpcbertoldo

# Description

Fix #662 by creating the parameter `n_features` (nb of features/axes retained by the dimension reduction).

I also made it possible to use a custom backbone without modifying the source code.
This was limited by this hardcoded dict

![image](https://user-images.githubusercontent.com/24547377/199137692-66d2c24b-3cb9-4acd-af03-9a60fbb86820.png)

If the backbone was not in the dict then the `orig_dims` and `emb_scale` could not be set.
These two don't need to be hardcoded, I made it be deduced from a dryrun feature extraction.

## Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which refactors the code base)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist

- [x] My code follows the [pre-commit style and check guidelines](https://openvinotoolkit.github.io/anomalib/guides/using_pre_commit.html#pre-commit-hooks) of this project.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes

2022-11-01 04:46 UTC, samet-akcay approved these changes
Thanks @jpcbertoldo. The timing of this PR is also great, given that we wanted to add Efficient backbone support.

2022-11-01 13:57 UTC, ashwinvaidya17 approved these changes
Looks good to me

2022-11-01 18:05 UTC, jpcbertoldo commented on anomalib/models/padim/torch_model.py
> +    "wide_resnet50_2": {"orig_dims": 1792, "emb_scale": 4},
Makes sense to me.
I kept it to have backwards compatibility but in fact the user doesn't see it.

2022-11-02 06:17 UTC, samet-akcay commented on anomalib/models/padim/torch_model.py
> +    "wide_resnet50_2": {"orig_dims": 1792, "emb_scale": 4},
I agree, this stuff is happening under the hood, and users are not aware of this. It would be alright to remove it.

2022-11-02 16:39 UTC, jpcbertoldo commented
done
i further simplified a bit

2022-11-04 14:20 UTC, djdameln commented on anomalib/models/padim/torch_model.py
> +def _deduce_dims(
Maybe it would be good to add a unit test for this function

2022-11-07 19:46 UTC, jpcbertoldo commented
> Maybe it would be good to add a unit test for this function

@djdameln it didn't feel right to have such a specific test.

Instead i extracted the dryrun part and tested that. The logic in `_deduce_dims` is trivial now.

2022-11-08 05:34 UTC, samet-akcay requested changes
There is going to be merge conflicts between this PR and #675. @ashwinvaidya17 and @jpcbertoldo, can you guys sync how to minimise/avoid these conflicts?

2022-11-08 08:11 UTC, jpcbertoldo commented
The conflict is only in `anomalib/models/components/feature_extractors/__init__.py` right?

Doesnt look so hard, whicever is merged second rebases.

@ashwinvaidya17 could you check if the new function in that file in #675 would work with the torchfx extractor? If not then it needs a subcase.

2022-11-08 10:56 UTC, jpcbertoldo commented
> > The conflict is only in `anomalib/models/components/feature_extractors/__init__.py` right?
> > Doesnt look so hard, whicever is merged second rebases.
> > @ashwinvaidya17 could you check if the new function in that file in #675 would work with the torchfx extractor? If not then it needs a subcase.
> 
> I am working on a design to make the feature extractor configurable. I think we can move dimension computation into the feature extractor class. Since the design might take time we can merge this one first and then I can update PR #675

Cool : )

2022-11-08 13:21 UTC, samet-akcay approved these changes

2022-11-08 14:07 UTC, merged