Fix >100% confidence issue for OpenVINO inference
openvinotoolkit/anomalib pull request #667
Opened 2022-11-02 13:32 UTC by djdameln

# Description

- Quick fix for the OpenVINO inference normalization issues.
- The problem was due to not normalizing the openvino outputs when in classification mode.
- Solved by making `anomaly_maps` argument optional in `Inferencer._normalize` and calling `_normalize` with only the pred scores in classification case.

This works as a quick fix, but I feel after this we should revisit the logic in `post_process` for the different inferencers.

- Fixes # (issue)

## Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which refactors the code base)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the [pre-commit style and check guidelines](https://openvinotoolkit.github.io/anomalib/guides/using_pre_commit.html#pre-commit-hooks) of this project.
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes

2022-11-02 13:48 UTC, samet-akcay requested changes
Thanks! only a single comment

2022-11-02 13:48 UTC, samet-akcay commented on anomalib/deploy/inferencers/openvino_inferencer.py
> +            assert anomaly_map is not None
Would it be an idea to add `else` here to raise a `ValueError` for the rest of the `task` values?

2022-11-02 13:54 UTC, ashwinvaidya17 approved these changes
Thanks for investigating!

2022-11-07 10:06 UTC, samet-akcay approved these changes

2022-11-07 10:06 UTC, merged