Update lightning_model.py
openvinotoolkit/anomalib pull request #700
Opened 2022-11-08 14:44 UTC by jpcbertoldo

- Fixes #699

## Changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which refactors the code base)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [] My code follows the [pre-commit style and check guidelines](https://github.com/openvinotoolkit/anomalib/blob/main/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes

2022-11-08 15:12 UTC, ashwinvaidya17 requested changes
I think the updated config is not synced with github.

2022-11-08 15:12 UTC, ashwinvaidya17 commented on anomalib/models/cflow/config.yaml
>    soft_permutation: false
Shouldn't this be renamed to `permute_soft`?

2022-11-08 15:12 UTC, ashwinvaidya17 commented on anomalib/models/cflow/config.yaml
> +  fiber_batch_size: 64
Since it is here now we can remove this from datasets.

2022-11-08 15:44 UTC, samet-akcay commented
I have the same comments

2022-11-08 15:49 UTC, jpcbertoldo commented
> I think the updated config is not synced with github.

I'm not sure what you mean but i changed what you said in the line comments.

2022-11-08 15:52 UTC, ashwinvaidya17 commented
> > I think the updated config is not synced with github.
> 
> I'm not sure what you mean but i changed what you said in the line comments.

I meant maybe you made the changes locally but forgot to push them.

2022-11-08 16:21 UTC, jpcbertoldo commented
The error is not the usual coverage upload but I'm not sure it is related to the PR.

![image](https://user-images.githubusercontent.com/24547377/200619346-1fc41244-4fe5-47a1-8490-926a1f44b089.png)

2022-11-09 04:51 UTC, samet-akcay commented
> The error is not the usual coverage upload but I'm not sure it is related to the PR.
> 
> ![image](https://user-images.githubusercontent.com/24547377/200619346-1fc41244-4fe5-47a1-8490-926a1f44b089.png)

Based on the [logs](https://github.com/openvinotoolkit/anomalib/actions/runs/3420984937/jobs/5696632200), looks like there is something wrong with this tests.
`tests/pre_merge/utils/callbacks/normalization_callback/test_normalization_callback.py F [ 95%]`

2022-11-09 10:28 UTC, jpcbertoldo commented
> > The error is not the usual coverage upload but I'm not sure it is related to the PR.
> > ![image](https://user-images.githubusercontent.com/24547377/200619346-1fc41244-4fe5-47a1-8490-926a1f44b089.png)
> 
> Based on the [logs](https://github.com/openvinotoolkit/anomalib/actions/runs/3420984937/jobs/5696632200), looks like there is something wrong with this tests. `tests/pre_merge/utils/callbacks/normalization_callback/test_normalization_callback.py F [ 95%]`

Thanks!
Will check it locally.

2022-11-09 15:45 UTC, jpcbertoldo commented
```
pre_merge_pytest run-test: commands[0] | python -m pytest /cluster/CMM/home/jcasagrandebertoldo/repos/anomalib/tests/pre_merge/utils/callbacks/normalization_callback/test_normalization_callback.py --showlocals
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.8.13, pytest-7.2.0, pluggy-1.0.0
cachedir: .tox/pre_merge_pytest/.pytest_cache
rootdir: /cluster/CMM/home/jcasagrandebertoldo/repos/anomalib
plugins: flaky-3.7.0, anyio-3.6.2
collected 1 item                                                                                                                                                                            

tests/pre_merge/utils/callbacks/normalization_callback/test_normalization_callback.py .                                                                                               [100%]

======================================================================== 1 passed, 33 warnings in 123.98s (0:02:03) =========================================================================
__________________________________________________________________________________________ summary __________________________________________________________________________________________
  pre_merge_pytest: commands succeeded
  congratulations :)
 *  Terminal will be reused by tasks, press any key to close it. 
 ```
 
No problems in my local tox :thinking:

2022-11-09 15:50 UTC, jpcbertoldo commented
Maybe some flaky effect? Is there a way to relaunch it @samet-akcay ?

2022-11-09 17:48 UTC, samet-akcay commented
> Maybe some flaky effect? Is there a way to relaunch it @samet-akcay ?

Re-running the tests now...

2022-11-09 18:26 UTC, jpcbertoldo commented
test_normalization_callback

> > Maybe some flaky effect? Is there a way to relaunch it @samet-akcay ?
> 
> Re-running the tests now...

Yeah, still.

I'm clueless here atm. I tried to search for "cflow" in the logs and there is nothing :thinking:

2022-11-11 07:37 UTC, samet-akcay commented
> test_normalization_callback
> 
> > > Maybe some flaky effect? Is there a way to relaunch it @samet-akcay ?
> > 
> > 
> > Re-running the tests now...
> 
> Yeah, still.
> 
> I'm clueless here atm. I tried to search for "cflow" in the logs and there is nothing 🤔
> 
> Rebasing to see what happens.

Looks like there is something wrong with the tests. I'm observing a similar behaviour on another PR as well. Something seems to be broken.

2022-11-11 08:30 UTC, jpcbertoldo commented
> > test_normalization_callback
> > > > Maybe some flaky effect? Is there a way to relaunch it @samet-akcay ?
> > > 
> > > 
> > > Re-running the tests now...
> > 
> > 
> > Yeah, still.
> > I'm clueless here atm. I tried to search for "cflow" in the logs and there is nothing thinking
> > Rebasing to see what happens.
> 
> Looks like there is something wrong with the tests. I'm observing a similar behaviour on another PR as well. Something seems to be broken.

There are also some badly configured tests I could not pass locally but they pass in the CI apparently.
See #704.
But it's another test: `tests/pre_merge/utils/callbacks/visualizer_callback/test_visualizer.py`

2022-11-21 09:23 UTC, jpcbertoldo commented
I think it's mergeable now?
The error now is the usual coverage report.

2022-11-21 09:25 UTC, samet-akcay commented
> I think it's mergeable now? The error now is the usual coverage report.

Yes, let's merge it! Thanks for the effort!

2022-11-21 09:25 UTC, merged