Adding segmentation to DFM
openvinotoolkit/anomalib pull request #743
Opened 2022-11-29 17:09 UTC by nahuja-intel

# Description

- Provide a summary of the modification as well as the issue that has been resolved. List any dependencies that this modification necessitates.

- Fixes # (issue)

## Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which refactors the code base)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the [pre-commit style and check guidelines](https://github.com/openvinotoolkit/anomalib/blob/main/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes

2022-12-01 09:30 UTC, ashwinvaidya17 requested changes
Minor comments but rest looks good. Thanks for the efforts!

2022-12-05 15:20 UTC, djdameln requested changes
Thanks, very nice addition! I just have some minor comments

2022-12-05 15:20 UTC, djdameln commented on anomalib/models/dfm/torch_model.py
> +    def score(self, features: Tensor, feature_shape) -> Tensor:
And maybe rename it to `feature_shapes` to be consistent with the naming elsewhere in the class.

2022-12-05 15:20 UTC, djdameln commented on anomalib/models/dfm/torch_model.py
>          elif self.score_type == "fre":
If I undertand correctly, segmentation is only supported when score_type is "fre"? Maybe you could mention this in the docstring of the method, and also in `anomalib/models/dfm/README.md`

2022-12-06 22:18 UTC, nahuja-intel commented
So, all the pre-commit checks, including isort, are passing when I commit locally. However isort is failing while requesting a PR. Any suggestions?

2022-12-07 08:31 UTC, ashwinvaidya17 reviewed
Thanks. One comment

2022-12-07 16:13 UTC, nahuja-intel commented on anomalib/models/dfm/README.md
> +In the anomaly classification stage, class-conditional PCA transformations and Gaussian Density models are learned. Two types of scores are calculated (i) Feature-reconstruction scores (norm of the d
Thanks for catching that. Yes, it should be "...supported by both score types". Any feedback on why the tox run failed? Anything I need to change in the code?

2022-12-12 11:33 UTC, ashwinvaidya17 requested changes

2022-12-12 11:33 UTC, ashwinvaidya17 commented on anomalib/models/dfm/lightning_model.py
> +        batch["pred_scores"], batch["anomaly_maps"] = self.model(batch["image"])
This needs to be assigned based on the score type. If I select `nll` score type then training fails.

2022-12-12 12:51 UTC, djdameln commented on anomalib/models/dfm/torch_model.py
> +            output = score, score_map
The torch inferencer expects the predictions of the torch model for the segmentation task type to be in the form (anomaly_map, anomaly_score), so these two should be reversed here (of course, the lightning model should then also be updated accordingly. 

This is what's causing the failing test case in the CI.

2022-12-13 07:47 UTC, ashwinvaidya17 approved these changes
Thanks for the efforts

2022-12-13 13:49 UTC, samet-akcay approved these changes
lgtm, thanks!

2022-12-19 13:33 UTC, djdameln approved these changes

2022-12-19 13:34 UTC, merged