Allow setting manual threshold in PL inference
openvinotoolkit/anomalib pull request #774
Opened 2022-12-07 16:46 UTC by djdameln

# Description

- This PR makes a few small changes which allows users to set a manual threshold when running lightning inference, even after the model has been trained with adaptive thresholding enabled. To use the manual threshold, the user can simply set the thresholding method to `manual` in the config, and specify the image and pixel-level thresholds. These values will then overwrite the adaptive threshold values which are loaded from the model weights.

- The model loading functionality in LoadModelCallback was moved from `on_test_start` and `on_predict_start`, which removes duplication and is more in line with the intended use of `setup`.
- By adding the model loader callback before the post-processing configuration callbacks, the threshold value is first loaded from the model file. Then, when setup is called in post-processing configuration callback, the thresholds are overwritten by the manual values specified by the user in the `config.yaml`.

Based on my experimentation I could not find any side effects of these changes, but it would be good if the reviewers could double check this on their side.

## Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which refactors the code base)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the [pre-commit style and check guidelines](https://github.com/openvinotoolkit/anomalib/blob/main/CONTRIBUTING.md) of this project.
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes

2022-12-08 06:59 UTC, ashwinvaidya17 approved these changes
Thanks. I feel we should document this behaviour somewhere though.

2022-12-08 07:17 UTC, samet-akcay approved these changes
I agree with @ashwinvaidya17. Would be great if we mention this somewhere in the documentation.

2022-12-08 07:57 UTC, djdameln commented
> Thanks. I feel we should document this behaviour somewhere though.

> I agree with @ashwinvaidya17. Would be great if we mention this somewhere in the documentation.

Yeah, I think we need an extensive guide in our documentation which explains the thresholding and normalization mechanisms of anomalib, and gives pointers on how to configure this. We're getting many questions in the discussion section on these topics.

2022-12-09 14:51 UTC, ashwinvaidya17 approved these changes
Thanks for updating the docs

2022-12-13 13:21 UTC, samet-akcay requested changes
thanks, just a single comment to properly render the rst file.

2022-12-13 13:21 UTC, samet-akcay commented on docs/source/tutorials/inference.rst
> +It is also possible to run inference with a custom anomaly score threshold that differs from the threshold used/computed during training. To change the threshold for inference, simply set the `metric
```suggestion
It is also possible to run inference with a custom anomaly score threshold that differs from the threshold used/computed during training. To change the threshold for inference, simply set the ``metrics.threshold.method`` to ``manual`` and specify the custom threshold values in ``metrics.threshold.manual_image`` and ``metrics.threshold.manual_pixel``.
```

2022-12-13 13:29 UTC, samet-akcay approved these changes

2022-12-13 16:27 UTC, merged